local:
  data_path: Resources/
  encoding: iso-8859-1
  dbow_model_path: model/doc2vec/persistence/model
  dm_model_path: model/doc2vec/persistence/dm/
  max_workers: 4
  vector_size: 100
  window: 5
  min_count: 5
  epochs: 10

zeus:
  data_path: /mnt/auto/people/plgamarciniec/SearchEngineDoc2Vec/Resources
  encoding: iso-8859-1
  dbow_model_path: /mnt/auto/people/plgamarciniec/SearchEngineDoc2Vec/model/doc2vec/persistance/dbow/
  dm_model_path: /mnt/auto/people/plgamarciniec/SearchEngineDoc2Vec/model/doc2vec/persistance/dm/
  max_workers: 16
  vector_size: 100
  window: 5
  min_count: 5
  epochs: 45


